import '@radix-ui/themes/styles.css';
import './theme-config.css';
import './globals.css';
import { Container, Theme } from '@radix-ui/themes';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from '@/app/NavBar';
import AuthProvider from '@/app/providers/AuthProvider';
import { QueryClientProvider } from '@/app/providers/QueryClientProvider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={inter.variable}>
      <body>
        <AuthProvider>
          <QueryClientProvider>
            <Theme appearance='light' accentColor='purple' radius='small'>
              <NavBar />
              <Container>
                <main className='p-5'>{children}</main>
              </Container>
            </Theme>
          </QueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
